from pptx import Presentation
from pptx.util import Inches
import tkinter
from tkinter import Tcl
from tkinter import filedialog
from datetime import datetime
from pptx.enum.text import PP_ALIGN
import re
import os
import glob
import pathlib


# Choosing folder with desired files:
file_path = filedialog.askdirectory( initialdir="/", title="Select Folder")

# Creating Blank PPT Presentation:
prs = Presentation()
# Slide dimensions
prs.slide_width = Inches(13.33)
prs.slide_height = Inches(7.5)
blank_slide_layout = prs.slide_layouts[1]

# subtitle/Autogenerated
number_subtitle = "Autogenerated " + datetime.now().strftime(
            '%Y-%m-%d %H:%M:%S')
# get the name of the series/sample of pictures from the name of the folder
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
folder_name = os.path.basename(file_path)
subtitle = slide.placeholders[1]

# title
title.text = folder_name
title.left = Inches(1.67)
title.top = Inches(1.23)
title.width = Inches(10)
title.height = Inches(2.63)
# subtitle
subtitle.text = number_subtitle
subtitle.left = Inches(1.67)
subtitle.top = Inches(3.94)
subtitle.width = Inches(10)
subtitle.height = Inches(1.81)

# Select folder with desired pictures:
pictures =[]
pictures = glob.glob(os.path.join(file_path, '*.tif'))
pictures.sort(key=lambda x:[int(c) if c.isdigit() else c for c in re.split(r'(\d+)', x)[-4:]])
#print(pictures)
os.chdir(file_path)

pic_pairs = zip(*[pictures[i::2] for i in range(2)])

blank_slide_layout = prs.slide_layouts[6]

left = Inches(.38)
top = Inches(6.75)
width = Inches(1.6)
height = Inches(0.44)

for pic_1, pic_2 in pic_pairs:
	slide = prs.slides.add_slide(blank_slide_layout)
	tb = slide.shapes.add_textbox(left, top, width, height)
	tb.text = pic_1.split('/')[-1]
	left = Inches(.38)
	top = Inches(7.1)
	width = Inches(1.6)
	height = Inches(.44)
	tb1 = tb = slide.shapes.add_textbox(left, top, width, height)
	tb1.text = pic_2.split('/')[-1]

	left = Inches(.38)
	top = Inches(.67)
	height = Inches(6.17)
	slide.shapes.add_picture(pic_1, left, top*1.5, height=height)
	left = Inches(6.79)
	slide.shapes.add_picture(pic_2, left, top*1.5, height=height)



prs.save(folder_name + ".pptx")
print("\nPPT Finished!")












